crer_empreender/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Avaliação
    url(r'^avaliacao/$', 'avaliacao.views.novo', name='avaliacao_novo'),
    url(r'^avaliacao/api/avaliacao/$', 'avaliacao.views.api_avaliacao', name='avaliacao_api_avaliacao'),
    # REST API
    url(r'^categoria/api/lista/$', 'categoria.views.api_lista', name='categoria_api_lista'),

    # Login
    url(r'^login/$', 'login.views.index', name='login_index'),
    url(r'^login/exit/$', 'login.views.exit', name='login_exit'),

    # Menu (DEFAULT PAGE)
    url(r'^$', 'menu.views.index', name='menu_index'),

    # Pesquisa
    url(r'^pesquisa/index/$', 'pesquisa.views.index', name='pesquisa_index'),
    url(r'^pesquisa/categoria/(?P<id>\d+)/$', 'pesquisa.views.categoria', name='pesquisa_categoria'),
    url(r'^pesquisa/nome_servico/$', 'pesquisa.views.nome_servico', name='pesquisa_nome_servico'),
    # REST API
    url(r'^pesquisa/api/prof_categ/$', 'pesquisa.views.api_prof_categ', name='categoria_api_prof_categ'),
    url(r'^pesquisa/api/nome/$', 'pesquisa.views.api_nome_servico', name='pesquisa_api_nome_servico'),

    # Usuário
    url(r'^usuario/$', 'usuario.views.novo', name='usuario_novo'),
    url(r'^usuario/(?P<id>\d+)/$', 'usuario.views.editar', name='usuario_editar'),
    # REST API
    url(r'^usuario/api/login/$', 'usuario.views.api_login', name='usuario_api_login'),
    url(r'^usuario/api/lista_profissional/$', 'usuario.views.api_lista_profissional', name='usuario_api_lista_profissional'),
    url(r'^usuario/api/criar_conta/$', 'usuario.views.api_criar_conta', name='usuario_api_criar_conta'),
    url(r'^usuario/api/consultar_perfil/$', 'usuario.views.api_consultar_perfil', name='usuario_api_consultar_perfil'),
    url(r'^usuario/api/editar_perfil/$', 'usuario.views.api_editar_perfil', name='usuario_api_editar_perfil'),

]

usuario/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    TIPO_CHOICES = (
        ('CLI', 'Cliente'),
        ('PRO', 'Profissional'),
    )

    tipo = models.CharField(
        u'Tipo(Sigla)',
        max_length=3,
        choices=TIPO_CHOICES,
    )
    user = models.OneToOneField(
        User,
        related_name='user_profile'
    )
    fone = models.CharField(
        u'Fone',
        max_length=15,
        blank=True,
        null=True,
    )
    servico = models.CharField(
        u'Serviço',
        max_length=256,
        blank=True,
    )
    foto = models.ImageField(
        u'Foto',
        blank=True,
    )
    categoria = models.ForeignKey(
        'categoria.Categoria',
        null=True,
    )

    class Meta:
        db_table = 'auth_user_profile'

    def __unicode__(self):
        return self.user.username

usuario/forms.py
# -*- coding: utf-8 -*-
from django import forms

from categoria.models import Categoria
from usuario.models import UserProfile


class UsuarioForm(forms.Form):
    tipo = forms.ChoiceField(
        choices=UserProfile.TIPO_CHOICES,
        label='Tipo',
        widget=forms.Select(attrs={'class': 'select'})
    )
    primeiro_nome = forms.CharField(
        label='Primeiro Nome',
        max_length=60,
    )
    ultimo_nome = forms.CharField(
        label='Último Nome',
        max_length=60,
    )
    email = forms.CharField(
        label='Email',
        max_length=60,
    )
    nome_usuario = forms.CharField(
        label='Usuário',
        max_length=30,

    )
    senha = forms.CharField(
        label='Senha',
        max_length=20,
        required=False,
    )
    conf_senha = forms.CharField(
        label='Confirmação de Senha',
        max_length=20,
        required=False,
    )
    fone = forms.CharField(
        label='Fone',
        max_length=20,
    )
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.all().order_by('nome'),
        label='Categoria',
        widget=forms.Select(attrs={'class': 'select'}),
        required = False,
    )
    servico = forms.CharField(
        label='Serviço/Produto',
        max_length=254,
        required=False,
    )

usuario/views.py
# -*- coding: utf-8 -*-
import json

from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms.forms import NON_FIELD_ERRORS
from django.forms.util import ErrorList
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from rest_framework.decorators import api_view

from usuario.forms import UsuarioForm
from usuario.models import UserProfile


# -= NOVO =-
def novo(request):
    form_action = "/usuario/"

    if request.POST:
        form = UsuarioForm(request.POST)
        if form.is_valid():
            form_valido = True

            if form.cleaned_data['senha'] != form.cleaned_data['conf_senha']:
                errors = form._errors.setdefault("senha", ErrorList())
                errors.append(u"As senhas não conferem.")
                form_valido = False

            if form.cleaned_data['tipo'] == "PRO" and form.cleaned_data['categoria'] is None:
                errors = form._errors.setdefault("categoria", ErrorList())
                errors.append(u"Deve ser informada.")
                form_valido = False

            if form.cleaned_data['tipo'] == "PRO" and form.cleaned_data['servico'] == "":
                errors = form._errors.setdefault("servico", ErrorList())
                errors.append(u"Deve ser informado.")
                form_valido = False

            if form_valido:
                # Verificar se nome usuário existe
                user = User.objects.filter(username=form.cleaned_data['nome_usuario'])

                if not user:
                    # Criar Novo Usuário
                    new_user = User()
                    new_user.username = form.cleaned_data['nome_usuario']
                    new_user.first_name = form.cleaned_data['primeiro_nome']
                    new_user.last_name = form.cleaned_data['ultimo_nome']
                    new_user.email = form.cleaned_data['email']
                    new_user.set_password(form.cleaned_data['senha'])
                    new_user.is_active = False
                    new_user.save()
                    # Atualizar Profile
                    user_profile = UserProfile.objects.get(user_id=new_user.id)
                    user_profile.tipo = form.cleaned_data['tipo']
                    user_profile.fone = form.cleaned_data['fone']
                    user_profile.categoria = form.cleaned_data['categoria']
                    user_profile.servico = form.cleaned_data['servico']
                    user_profile.save()

                    form.errors[NON_FIELD_ERRORS] = form.error_class(["Conta criada com sucesso."])
                    return render(request, 'usuario/conta_criada.html', {})
                else:
                    errors = form._errors.setdefault("nome_usuario", ErrorList())
                    errors.append(u"Nome de usuário já está em uso.")

    else:
        form = UsuarioForm()
        form.fields['tipo'].initial = ""
        form.fields['primeiro_nome'].initial = ""
        form.fields['ultimo_nome'].initial = ""
        form.fields['email'].initial = ""
        form.fields['nome_usuario'].initial = ""
        form.fields['senha'].initial = ""
        form.fields['conf_senha'].initial = ""
        form.fields['fone'].initial = ""
        form.fields['categoria'].initial = ""
        form.fields['servico'].initial = ""

    form_caption = "Criar Conta"
    return render(request, 'usuario/form.html', {'form': form,
                                                 'form_action': form_action,
                                                 'form_caption': form_caption})


# -= EDITAR =-
@login_required
def editar(request, id):
    form_action = "/usuario/"+id+"/"
    form_caption = "Alterar Perfil"

    user = get_object_or_404(User, id=id)

    if request.POST:
        form = UsuarioForm(request.POST)

        if form.is_valid():
            # Atualizar Usuário
            user.username = form.cleaned_data['nome_usuario']
            user.first_name = form.cleaned_data['primeiro_nome']
            user.last_name = form.cleaned_data['ultimo_nome']
            user.email = form.cleaned_data['email']
            user.save()
            # Atualizar Profile
            user_profile = UserProfile.objects.get(user_id=user.id)
            user_profile.tipo = form.cleaned_data['tipo']
            user_profile.fone = form.cleaned_data['fone']
            user_profile.categoria = form.cleaned_data['categoria']
            user_profile.servico = form.cleaned_data['servico'].strip(' \t\n\r')
            user_profile.save()

            return render(request, 'usuario/perfil_alterado.html', {})
        else:
            return render(request, 'usuario/form.html', {'form_caption': form_caption,
                                                         'form_action': form_action,
                                                         'form': form})
    else:
        user_profile = UserProfile.objects.get(user_id=user.id)

        form = UsuarioForm()
        form.fields['tipo'].initial = user_profile.tipo
        form.fields['primeiro_nome'].initial = user.first_name
        form.fields['ultimo_nome'].initial = user.last_name
        form.fields['email'].initial = user.email
        form.fields['nome_usuario'].initial = user.username
        form.fields['senha'].initial = ""
        form.fields['conf_senha'].initial = ""
        form.fields['fone'].initial = user_profile.fone
        form.fields['categoria'].initial = user_profile.categoria
        form.fields['servico'].initial = user_profile.servico.strip(' \t\n\r')

    return render(request, 'usuario/form.html', {'form_caption': form_caption,
                                                 'form_action': form_action,
                                                 'form': form})


"""
||||||||||||||||||||||||
|                      |
|    -= REST API =-    |
|                      |
||||||||||||||||||||||||
"""


@api_view(['POST'])
def api_login(request):

    if request.POST:

        user = authenticate(username=request.POST['usuario'], password=request.POST['senha'])

        if user:
            if user.is_active:
                ret_json = {
                    'id': user.id,
                    'first_name': user.first_name,
                    'last_name': user.last_name,
                    'superuser': user.is_superuser,
                    'mensagem': 'Login Efetuado.',
                    'status': 'OK'
                }
            else:
                ret_json = {
                    'mensagem': 'Usuário não foi ativado.',
                    'status': 'INATIVO'
                }
        else:
            ret_json = {
                'nome': None,
                'mensagem': "Usuário ou senha não confere.",
                'status': "NAO_ENCONTRADO"
            }
    else:
        ret_json = {
            'mensagem': 'Problema ao efetuar login.',
            'status': 'ERRO'
        }

    return HttpResponse(json.dumps(ret_json), "application/json")


@api_view(['POST'])
def api_criar_conta(request):

    if request.POST:

        try:
            # Verificar se nome usuário existe
            user = User.objects.filter(username=request.POST['n_usuario'])

            if not user:
                # Criar Novo Usuário
                new_user = User()
                new_user.username = request.POST['n_usuario']
                new_user.first_name = request.POST['p_nome']
                new_user.last_name = request.POST['u_nome']
                new_user.email = request.POST['email']
                new_user.set_password(request.POST['senha'])
                new_user.is_active = False
                new_user.save()
                # Atualizar Profile
                user_profile = UserProfile.objects.get(user_id=new_user.id)
                user_profile.tipo = request.POST['tipo']
                user_profile.fone = request.POST['fone']
                if request.POST['categoria']:
                    user_profile.categoria_id = request.POST['categoria']
                if request.POST['serv_prod']:
                    user_profile.servico = request.POST['serv_prod']

                user_profile.save()

                ret_json = {'mensagem': 'Conta Criada com Sucesso!'}
            else:
                ret_json = {'mensagem': 'JA_EXISTE'}

        except Exception as e:
            ret_json = {'mensagem': 'Erro->' + e.message}

        return HttpResponse(json.dumps(ret_json), "application/json")


@api_view(['POST'])
def api_consultar_perfil(request):
    if request.POST:

        user = User.objects.get(id=request.POST['user_id'])
        user_profile = UserProfile.objects.get(user_id=user.id)
        if user:
            ret_json = {
                'id': user.id,
                'tipo': user_profile.tipo,
                'nome': user.first_name,
                'sobrenome': user.last_name,
                'email': user.email,
                'usuario': user.username,
                'fone': user_profile.fone,
                'categoria': user_profile.categoria_id,
                'servprod': user_profile.servico,
            }
    else:
        ret_json = {'mensagem': 'ERRO'}

    return HttpResponse(json.dumps(ret_json), "application/json")


@api_view(['POST'])
def api_editar_perfil(request):

    if request.POST:

        try:
            user = User.objects.get(id=request.POST['id'])
            if user:
                user.first_name = request.POST['nome']
                user.last_name = request.POST['sobrenome']
                # user.username = request.POST['usuario']
                user.email = request.POST['email']
                user.save()
                # Atualizar Profile
                user_profile = UserProfile.objects.get(user_id=user.id)
                user_profile.tipo = request.POST['tipo']

templates/usuario/conta_criada.html
{% extends 'base.html' %}

{% block content %}

<div class="col-xs-6 col-md-offset-3 transparency2">

    <div class="panel panel-default">
        <div class="panel-body" align="center">
            <h1 class="text-success">
                <i class="glyphicon glyphicon-thumbs-up"></i>
            </h1>
            <h3 class="text-primary">
                Conta criada com sucesso.
                Aguarde ativação da sua conta.
            </h3>
        </div>

        <div class="panel-footer textCenter">
            <a href="{% url 'login_index' %}" class="btn btn-success">Acessar o sistema</a>
        </div>

    </div>

</div>

{% endblock %}

templates/usuario/form.html
{% extends 'base.html' %}

{% block content %}

{% if form_caption == 'Alterar Perfil' %}
<div class="col-xs-12 row transparency2">
    <div class="btn-group btn-breadcrumb transparency">
        <a href="{% url 'login_index' %}" class="btn btn-primary" title="Ir para Login"><i class="icon-switch"></i></a>
        <a href="{% url 'menu_index' %}" class="btn btn-primary" title="Ir para Menu Principal"><i class="glyphicon glyphicon-home"></i></a>
        <a href="#" class="btn btn-primary">{{ form_caption }}</a>
    </div>
</div>
{% elif form_caption == 'Criar Conta' %}

    <div class="col-xs-12 row transparency2">
    <div class="btn-group btn-breadcrumb transparency2">
        <a href="{% url 'login_index' %}" class="btn btn-primary"><i class="icon-switch"></i></a>
        <a href="#" class="btn btn-primary">Criar Conta</a>
    </div>
</div>
{% endif %}

<div class="col-xs-6 col-md-offset-3" xmlns="http://www.w3.org/1999/html">

    <div class="panel panel-default transparency2">

        <!--
        {% if form_caption == 'Criar Conta' %}
        <div class="panel-heading" style="background-color: #2e6da4; color: #fff; font-size: 16px;">
            {{ form_caption }}
        </div>
        {% endif %}
        -->

        <form action='{{ form_action }}' method='POST' >
            {% csrf_token %}

            <div class="panel-body" align="left">

                <div class="row col-xs-12">
                    {% include "form_messages.html" %}
                </div>

                <div class="row">
                    <div class="form-group col-xs-12">
                        <label for='id_tipo'>{{ form.tipo.label }}</label>
                        {{ form.tipo }}
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-6">
                        <label for='id_primeiro_nome'>{{ form.primeiro_nome.label }}</label>
                        <input id='id_primeiro_nome' name='primeiro_nome' value='{{ form.primeiro_nome.value }}' type='text' class='form-control' autocomplete="off" autofocus />
                    </div>
                    <div class="form-group col-xs-6">
                        <label for='id_ultimo_nome'>{{ form.ultimo_nome.label }}</label>
                        <input id='id_ultimo_nome' name='ultimo_nome' value='{{ form.ultimo_nome.value }}' type='text' class='form-control' autocomplete="off" autofocus />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-6">
                        <label for='id_email'>{{ form.email.label }}</label>
                        <input id='id_email' name='email' value='{{ form.email.value }}' type='text' class='form-control' autocomplete="off"/>
                    </div>
                    <div class="form-group col-xs-6">
                        <label for='id_email'>Nome de Usuário</label>
                        <input id='id_nome_usuario' name='nome_usuario' value='{{ form.nome_usuario.value }}' type='text' class='form-control' autocomplete="off"/>
                    </div>
                </div>

                <div class="row">
                {% if form_caption == 'Criar Conta' %}
                    <div class="form-group col-xs-6">
                        <label for='id_senha'>{{ form.senha.label }}</label>
                        <input id='id_senha' name='senha' value='{{ form.senha.value }}' type='password' maxlength="15" class='form-control' autocomplete="off"/>
                    </div>

                    <div class="form-group col-xs-6">
                        <label for='id_conf_senha'>{{ form.conf_senha.label }}</label>
                        <input id='id_conf_senha' name='conf_senha' value='{{ form.conf_senha.value }}' type='password' maxlength="15" class='form-control' autocomplete="off"/>
                    </div>
                {% endif %}
                </div>

                <div class="row">
                    <div class="form-group col-xs-6">
                        <label for='id_fone'>{{ form.fone.label }}</label>
                        <input id='id_fone' name='fone' value='{{ form.fone.value }}' type='text' class='form-control mask-phone_ddd' autocomplete="off" />
                    </div>

                    <div class="form-group col-xs-6">
                        <label for='id_fone'>{{ form.categoria.label }}</label>
                        {{ form.categoria }}
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-12">
                        <label for='id_servico'>{{ form.servico.label }}</label>
                        <textarea id='id_servico' name='servico' maxlength="256" wrap="soft" rows="4" class='form-control'>{{form.servico.value}}</textarea>
                    </div>
                </div>
            </div>

            <div class="panel-footer textCenter">
                <input type='submit' value='Salvar' id='btn_salvar' class="btn btn-success" />
            </div>
        </form>

    </div>

</div>

{% endblock %}

templates/usuario/perfil_alterado.html
{% extends 'base.html' %}

{% block content %}

<div class="col-xs-6 col-md-offset-3">

    <div class="panel panel-default">
        <div class="panel-body" align="center">
            <h1 class="text-success">
                <i class="glyphicon glyphicon-thumbs-up"></i>
            </h1>
            <h3 class="text-primary">
                Perfil alterado com sucesso!
            </h3>
        </div>

        <div class="panel-footer textCenter">
            <a href="{% url 'menu_index' %}" class="btn btn-success">Voltar ao menu</a>
        </div>

    </div>

</div>

{% endblock %}