crer_empreender/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Avaliação
    url(r'^avaliacao/$', 'avaliacao.views.novo', name='avaliacao_novo'),
    url(r'^avaliacao/api/avaliacao/$', 'avaliacao.views.api_avaliacao', name='avaliacao_api_avaliacao'),
    # REST API
    url(r'^categoria/api/lista/$', 'categoria.views.api_lista', name='categoria_api_lista'),

    # Login
    url(r'^login/$', 'login.views.index', name='login_index'),
    url(r'^login/exit/$', 'login.views.exit', name='login_exit'),

    # Menu (DEFAULT PAGE)
    url(r'^$', 'menu.views.index', name='menu_index'),

    # Pesquisa
    url(r'^pesquisa/index/$', 'pesquisa.views.index', name='pesquisa_index'),
    url(r'^pesquisa/categoria/(?P<id>\d+)/$', 'pesquisa.views.categoria', name='pesquisa_categoria'),
    url(r'^pesquisa/nome_servico/$', 'pesquisa.views.nome_servico', name='pesquisa_nome_servico'),
    # REST API
    url(r'^pesquisa/api/prof_categ/$', 'pesquisa.views.api_prof_categ', name='categoria_api_prof_categ'),
    url(r'^pesquisa/api/nome/$', 'pesquisa.views.api_nome_servico', name='pesquisa_api_nome_servico'),

    # Usuário
    url(r'^usuario/$', 'usuario.views.novo', name='usuario_novo'),
    url(r'^usuario/(?P<id>\d+)/$', 'usuario.views.editar', name='usuario_editar'),
    # REST API
    url(r'^usuario/api/login/$', 'usuario.views.api_login', name='usuario_api_login'),
    url(r'^usuario/api/lista_profissional/$', 'usuario.views.api_lista_profissional', name='usuario_api_lista_profissional'),
    url(r'^usuario/api/criar_conta/$', 'usuario.views.api_criar_conta', name='usuario_api_criar_conta'),
    url(r'^usuario/api/consultar_perfil/$', 'usuario.views.api_consultar_perfil', name='usuario_api_consultar_perfil'),
    url(r'^usuario/api/editar_perfil/$', 'usuario.views.api_editar_perfil', name='usuario_api_editar_perfil'),

]

avaliacao/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class Avaliacao(models.Model):

    profissional = models.ForeignKey(
        User,
        db_column='profissional_id',
        related_name='aval_profissional_id_fk',
    )
    avaliador = models.ForeignKey(
        User,
        db_column='avaliador_id',
        related_name='aval_avaliador_id_fk',
    )
    nota_atendimento = models.IntegerField(
        u'Atendimento',
    )
    nota_pontualidade = models.IntegerField(
        u'Pontualizade',
    )
    nota_preco = models.IntegerField(
        u'Preço',
    )
    nota_qualidade = models.IntegerField(
        u'Qualidade',
    )
    nota_recomendacao = models.IntegerField(
        u'Recomendação',
    )
    data = models.DateField(
        u'Data',
    )
    hora = models.TimeField(
        u'Hora',
    )

    class Meta:
        db_table = 'avaliacao'

    def __unicode__(self):
        return self.profissional.nome

avaliacao/forms.py
# -*- coding: utf-8 -*-
from django import forms

from avaliacao.models import Avaliacao
from django.contrib.auth.models import User


class AvaliacaoForm(forms.ModelForm):
    profissional = forms.ModelChoiceField(
        queryset=User.objects.all().order_by('first_name'),
        empty_label="Escolha um profissional",
        label='Profissional',
        widget=forms.Select(attrs={'class': 'select'})
    )

    class Meta:
        model = Avaliacao

        exclude = [
            'id',
        ]

avaliacao/views.py
# -*- coding: utf-8 -*-
import json

from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from rest_framework.decorators import api_view
from django.http import HttpResponse

from avaliacao.forms import AvaliacaoForm
from avaliacao.models import Avaliacao


# -= NOVO =-
@login_required
def novo(request):

    if request.POST:
        form = AvaliacaoForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'avaliacao/avaliacao_efetuada.html', {})
        else:
            print "--> ERROR: " + str(form.errors)
    else:
        form = AvaliacaoForm()
        form.fields['avaliador'].initial = request.user.id
        form.fields['data'].initial = datetime.now().strftime("%Y-%m-%d")
        form.fields['hora'].initial = datetime.now().strftime("%H:%M")

    return render(request, 'avaliacao/form.html', {'form': form})


@api_view(['POST'])
def api_avaliacao(request):

    if request.POST:

        try:
            avaliacao = Avaliacao()

            avaliacao.profissional_id = request.POST['prof_id']
            avaliacao.nota_atendimento = request.POST['aval_atend']
            avaliacao.nota_qualidade = request.POST['aval_qualid']
            avaliacao.nota_pontualidade = request.POST['aval_pontual']
            avaliacao.nota_preco = request.POST['aval_prec']
            avaliacao.nota_recomendacao = request.POST['aval_recom']
            avaliacao.avaliador_id = request.POST['user_id']
            avaliacao.data = datetime.now().strftime("%Y-%m-%d")
            avaliacao.hora = datetime.now().strftime("%H:%M")

            avaliacao.save()

            ret_json = {
                'mensagem': 'Avaliação salva!',
                'status': 'OK'
            }
        except Exception as e:
            ret_json = [{
                'mensagem': e.message,
                'status': 'ERRO'
            }]

        return HttpResponse(json.dumps(ret_json), "application/json")

templates/avaliacao/avaliacao_efetuada.html
{% extends 'base.html' %}

{% block content %}

<div class="col-xs-6 col-md-offset-3">

    <div class="panel panel-default">
        <div class="panel-body" align="center">
            <h1 class="text-success">
                <i class="glyphicon glyphicon-thumbs-up"></i>
            </h1>
            <h3 class="text-primary">
                Avaliação gravada com sucesso!
            </h3>
        </div>

        <div class="panel-footer textCenter">
            <a href="{% url 'menu_index' %}" class="btn btn-success">Voltar ao menu</a>
        </div>

    </div>

</div>

{% endblock %}

templates/avaliacao/form.html
{% extends 'base.html' %}

{% block content %}

<div class="col-xs-12 row transparency2">
    <div class="btn-group btn-breadcrumb transparency2">
        <a href="{% url 'login_index' %}" class="btn btn-primary" title="Ir para Login"><i class="icon-switch"></i></a>
        <a href="{% url 'menu_index' %}" class="btn btn-primary" title="Ir para Menu Principal"><i class="glyphicon glyphicon-home"></i></a>
        <a href="#" class="btn btn-primary">Avaliação</a>
    </div>
</div>
<div style="height: 60px;"></div>


<div class="col-xs-6 col-md-offset-3 transparency2">

    <div class="panel panel-default">

        <form action='.' method='POST'>
            {% csrf_token %}

            <input id='id_data' name='data' value='{{ form.data.value }}' type=text' hidden/>
            <input id='id_hora' name='hora' value='{{ form.hora.value }}' type=text' hidden />
            <input id='id_avaliador' name='avaliador' value='{{ form.avaliador.value }}' type=text' hidden />

            <div class="panel-body" align="left">

                <div class="row">
                    <div class="form-group col-xs-3">
                        <label for='id_profissional'>Profissional</label>
                    </div>
                    <div class="form-group col-xs-9">
                        {{ form.profissional }}
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-3">
                        <label for="exampleInputEmail1">Atendimento</label>
                    </div>
                    <div class="form-group col-xs-3">
                        <select id="id_nota_atendimento" name="nota_atendimento" class='form-control'>
                            <option value="1" >1</option>
                            <option value="2" >2</option>
                            <option value="3" >3</option>
                            <option value="4" >4</option>
                            <option value="5" >5</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-3">
                        <label for="exampleInputEmail1">Qualidade</label>
                    </div>
                    <div class="form-group col-xs-3">
                        <select id="id_nota_qualidade" name="nota_qualidade" class='form-control'>
                            <option value="1" >1</option>
                            <option value="2" >2</option>
                            <option value="3" >3</option>
                            <option value="4" >4</option>
                            <option value="5" >5</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-3">
                        <label for="exampleInputEmail1">Pontualidade</label>
                    </div>
                    <div class="form-group col-xs-3">
                        <select id="id_nota_pontualidade" name="nota_pontualidade" class='form-control'>
                            <option value="1" >1</option>
                            <option value="2" >2</option>
                            <option value="3" >3</option>
                            <option value="4" >4</option>
                            <option value="5" >5</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-3">
                        <label for="exampleInputEmail1">Preço</label>
                    </div>
                    <div class="form-group col-xs-3">
                        <select id="id_nota_preco" name="nota_preco" class='form-control'>
                            <option value="1" >1</option>
                            <option value="2" >2</option>
                            <option value="3" >3</option>
                            <option value="4" >4</option>
                            <option value="5" >5</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-3">
                        <label for="exampleInputEmail1">Recomendação</label>
                    </div>
                    <div class="form-group col-xs-3">
                        <select id="id_nota_recomendacao" name="nota_recomendacao" class='form-control'>
                            <option value="1" >1</option>
                            <option value="2" >2</option>
                            <option value="3" >3</option>
                            <option value="4" >4</option>
                            <option value="5" >5</option>
                        </select>
                    </div>
                </div>

            </div>

            <div class="panel-footer textCenter">
                <input type='submit' value='Avaliar' id='btn_salvar' class="btn btn-success" />
            </div>

        </form>

    </div>
</div>

{% endblock %}